### ISSUE TITLE
api.newgrounds.app doesn't provide song info any more

### ISSUE THREAD

**Issue by SamLukeYes** [SamLukeYes/GDCSD#1]
I'm looking for a new way to get download URL.

**Comment by WEGFan** [comment]
可以试试 `http://gdtools.wegfan.cn/ngsong/getSongInfo?songId=` 然后调用 `http://gdtools.wegfan.cn/ngsong/download?songId=` 下载文件，我弄了个代理，国内下载速度应该会更快一些

**Comment by SamLukeYes** [comment]
> 可以试试 `http://gdtools.wegfan.cn/ngsong/getSongInfo?songId=` 然后调用 `http://gdtools.wegfan.cn/ngsong/download?songId=` 下载文件，我弄了个代理，国内下载速度应该会更快一些

我现在直接通过解析 `newgrounds.com/audio/listen/{id}` 的内容来获取下载链接
